<a href="https://colab.research.google.com/github/rn771431-cmd/chatbot/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as py
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("T2-Superstore.csv", encoding="cp1252")

Saving T2-Superstore.csv to T2-Superstore.csv

In [2]:
df.head()
df.tail()
df.shape
df.info()
df.describe()
df.columns.tolist()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

DATA CLEANING

In [3]:
df.duplicated().sum()
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64


ENCODING

In [4]:
from sklearn.preprocessing import LabelEncoder
# to give categroical value
ctg = df.select_dtypes(include='object').columns
ctg

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')

In [5]:
le = LabelEncoder()
le
binary_columns=['Ship Mode', 'Segment', 'Region', 'Category', 'Sub-Category']
for column in binary_columns :
                  df[column] = le.fit_transform(df[column])

TRAIN TEST SPLIT

In [6]:
from sklearn.model_selection import train_test_split
x = df[["Segment"]]
y = df[["Region"]]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

MODEL BUILDING

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [8]:
# To display coefficients
model.coef_

# display intercept
model.intercept_

array([1.5828329])

In [9]:
#to predict values
y_pred = model.predict(x_test)
y_pred

array([[1.55837396],
       [1.5828329 ],
       [1.55837396],
       ...,
       [1.5828329 ],
       [1.55837396],
       [1.53391502]])

In [10]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("R2 Score :", r2_score(y_test, y_pred))

MAE : 1.0548396049962263
MSE : 1.3504692086334529
R2 Score : -0.0016888193418924669